export const USER_ERRORS = {
  NO_NAME: "Please enter your name",
  NO_EMAIL: "Please enter your email",
  INVALID_EMAIL: "Please enter a valid email",
  NO_PASSWORD: "Please enter your password",
  PASSWORD_LENGTH: "Minimum password length is 8 characters",
  ALREADY_EXISTS: "User already exists",
  PASSWORDS_DONT_MATCH: "Passwords do not match",
  NO_LOGIN_METHOD: "Please select a login method",
  DOESNT_EXIST: "User does not exist",
  INCORRECT_PASSWORD: "Incorrect password",
  OTP_DOESNT_MATCH: "OTP does not match",
  NOTHING_TO_UPDATE: "Nothing to update",
  OLD_NEW_SAME: "Old and new password cannot be the same",
};
